sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
- 2.5.1

addons:
  apt:
    packages:
      - make
      - pandoc
      - libxslt-dev
      - libxml2-dev
      - zlib1g-dev

before_install:
  - gem install jekyll bundler
  - gem uninstall nokogiri

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - make
  - echo "# This branch is for deployment only" >> _site/README.md

# Deploy to gh-pages branch
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: _site
  on:
    branch: master

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f64888ca9e483f08d91f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
